---
- name: Deploy Voting App
  hosts: your_servers
  become: yes
  tasks:
    - name: Ensure Python is installed
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

    - name: Copy code of voting-app
      ansible.builtin.copy:
        src: ./azure-vote
        dest: /opt/voting-app

    - name: Install dependencies
      ansible.builtin.command: pip install -r /opt/voting-app/requirements.txt
