---
- name: Setup voting-app
  hosts: all
  become: true
  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Ensure python is installed
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

    - name: Copy code of voting-app
      git:
        repo: https://github.com/yourusername/voting-app.git
        dest: /opt/voting-app

    - name: Install dependencies
      command: pip install -r /opt/voting-app/requirements.txt
