name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy with Docker Compose
        run: docker-compose up -d
        background: true

