name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy-docker-compose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Docker Compose
        run: docker-compose up -d

      - name: Run unit tests
        run: python /opt/voting-app/unit_tests.py
