name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  lint-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Lint Python code
        run: pylint your_python_code.py

  security-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Security check
        # Run security scanning tool here (e.g., Bandit, SonarQube, etc.)

  build-and-push-image:
    runs-on: ubuntu-latest
    needs: [lint-python, security-check]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: packer build packer_template.json

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker load -i /path/to/exported/image.tar && docker push madfire/voting-app:latest
