name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  lint-python-and-security-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint Python code
        run: flake8 azure-vote/main.py

      - name: Security check
        run: bandit -r azure-vote/main.py

  build-and-push-image:
    runs-on: ubuntu-latest
    needs: [lint-python-and-security-check]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: packer build packer/deploy.hcl

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker load -i /path/to/exported/image.tar && docker push madfire/voting-app:latest
